GET http://localhost:3000/api/course/byCluster?Cluster=PATNA
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMCwidXNlcm5hbWUiOiJtYXN0ZXJfYWRtaW4iLCJpYXQiOjE2Nzc2MDEzNTMsImV4cCI6MTY3NzY4Nzc1M30.YX7koMHnR58EcKlshBQKFnWTB_41CM8j6jp6yz6UeZ8

###
POST http://localhost:3000/api/course/updateDate?collegeId=101
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMCwidXNlcm5hbWUiOiJtYXN0ZXJfYWRtaW4iLCJpYXQiOjE2Nzc2MDEzNTMsImV4cCI6MTY3NzY4Nzc1M30.YX7koMHnR58EcKlshBQKFnWTB_41CM8j6jp6yz6UeZ8
Content-Type: application/json

{
    "key":"Innovation_Design_Thinking",
    "endDate":"2000-01-01T00:00:00.000Z",
    "startDate":"2000-01-01T00:00:00.000Z"
}

###
GET http://localhost:3000/api/course/byCollegeId?collegeId=101
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMCwidXNlcm5hbWUiOiJtYXN0ZXJfYWRtaW4iLCJpYXQiOjE2Nzc2MDEzNTMsImV4cCI6MTY3NzY4Nzc1M30.YX7koMHnR58EcKlshBQKFnWTB_41CM8j6jp6yz6UeZ8

