GET http://localhost:3000/api/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMSwidXNlcm5hbWUiOiJ1c2VyMSIsImlhdCI6MTY3NDIxNjUyNn0.8R5r_aXyKSvnAnodU8fKqJnlsrMchhb4NM-AtMh7EKI

{
    "form_Id":3002
}

###
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "username":"user2",
    "password":"pass2"
}

###
GET http://localhost:3000/api/getId/?id=101&form_Id=1001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMSwidXNlcm5hbWUiOiJ1c2VyMSIsImlhdCI6MTY3NDE5OTk1Mn0.1qohmxoLzIWWIvrAjX9-ndFrZG6rS-DdjEuh54Qz7fY

###
GET http://localhost:3000/api/getCluster/?form_Id=3002&cluster=Munger
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMSwidXNlcm5hbWUiOiJ1c2VyMSIsImlhdCI6MTY3NDE5OTk1Mn0.1qohmxoLzIWWIvrAjX9-ndFrZG6rS-DdjEuh54Qz7fY



###
PATCH http://localhost:3000/api/update_tmp/?id=110&form_Id=1001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMiwidXNlcm5hbWUiOiJ1c2VyMiIsImlhdCI6MTY3NDQ2MzEzN30.Bsn0HespkCpOQy3QxplYqCVwGpPc_2gdmY9q6uIrgZY

{
    "AC":-1,
    "Flooring":-1,
    "UPS":-1,
    "Cleaning":-1
}


###
# DELETE http://localhost:3000/id/160

GET http://localhost:3000/api/form
Content-Type: application/json

{
    "form_Id":1002
}