GET http://localhost:3000/api/college/dataDashboard/?form_Id=1001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMywidXNlcm5hbWUiOiJ1c2VyMyIsImlhdCI6MTY3NzQyNzYxNCwiZXhwIjoxNjc3NTE0MDE0fQ.Kb-U047RkxzVC-Wugk33r2a9TvAdlDb3RFSX3y3tDfE

###
GET http://localhost:3000/api/college/test/?formCode=4000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMywidXNlcm5hbWUiOiJ1c2VyMyIsImlhdCI6MTY3Nzc0OTc3MiwiZXhwIjoxNjc3ODM2MTcyfQ.iuMSGsAQsOldmRf-GItotM39IqTzIgPsuVvrlNVOZHo


###
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "username":"civ_admin_1",
    "password":"H)s"
}

###
GET http://localhost:3000/api/college/getId/?id=101&form_Id=4001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwidXNlcm5hbWUiOiJjaXZfYWRtaW5fMiIsInVzZXJTdGF0ZSI6IlRhbWlsX05hZHUiLCJpYXQiOjE2Nzc4NjkzMjUsImV4cCI6MTY3Nzk1NTcyNX0.QINHkgPKxQzX0HUUHno3sdk8sYttXgjB-W3El8_Bhvc

###
GET http://localhost:3000/api/getCluster/?form_Id=1001&cluster=PATNA
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMSwidXNlcm5hbWUiOiJ1c2VyMSIsImlhdCI6MTY3NTIzMjA5MiwiZXhwIjoxNjc1MjM1NjkyfQ.YiE71xcuNUUEPqgMYkxHz3gaR152rc2YJQcCQF7_04g


###
PATCH http://localhost:3000/api/college/update_tmp/?id=101&form_Id=5001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwidXNlcm5hbWUiOiJjaXZfYWRtaW5fMiIsInVzZXJTdGF0ZSI6IlRhbWlsX05hZHUiLCJpYXQiOjE2Nzc4NjkzMjUsImV4cCI6MTY3Nzk1NTcyNX0.QINHkgPKxQzX0HUUHno3sdk8sYttXgjB-W3El8_Bhvc

{
    "AC": 1
}

###
GET http://localhost:3000/api/college/lastChanges?form_Id=20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMywidXNlcm5hbWUiOiJ1c2VyMyIsImlhdCI6MTY3Nzc0OTc3MiwiZXhwIjoxNjc3ODM2MTcyfQ.iuMSGsAQsOldmRf-GItotM39IqTzIgPsuVvrlNVOZHo

###
GET http://localhost:3000/api/college/deleteAllLogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMywidXNlcm5hbWUiOiJ1c2VyMyIsImlhdCI6MTY3NzQyNjAyMiwiZXhwIjoxNjc3NTEyNDIyfQ.HSx006YXdyReOh8vJv-l4QkclzvzGoHwUPKW1xn_K4k

###
# DELETE http://localhost:3000/id/160


###
POST http://localhost:3000/note/addNote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMSwidXNlcm5hbWUiOiJ1c2VyMSIsImlhdCI6MTY3NTM1ODA1NCwiZXhwIjoxNjc1MzYxNjU0fQ.Ks95lhWTHkhlgghe3N2mi_sfc3_lsehGjuXT5_vTU9A

{
    "title":"seventh Note added",
    "content":"seven",
    "designation":"director"
}


# note.js REQUESTS
###
GET http://localhost:3000/note/allNotes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMSwidXNlcm5hbWUiOiJ1c2VyMSIsImlhdCI6MTY3NTM1ODA1NCwiZXhwIjoxNjc1MzYxNjU0fQ.Ks95lhWTHkhlgghe3N2mi_sfc3_lsehGjuXT5_vTU9A
###
GET http://127.0.0.1:3000/note/latestNotes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMSwidXNlcm5hbWUiOiJ1c2VyMSIsImlhdCI6MTY3NTI1MTk3OCwiZXhwIjoxNjc1MjU1NTc4fQ.lQ3igRt8u83ZtJK3XtUdd9NA_Wsp_UbMPQPa6et2ow8
###
POST http://localhost:3000/note/deleteNote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMSwidXNlcm5hbWUiOiJ1c2VyMSIsImlhdCI6MTY3NTI1MTk3OCwiZXhwIjoxNjc1MjU1NTc4fQ.lQ3igRt8u83ZtJK3XtUdd9NA_Wsp_UbMPQPa6et2ow8

{
    "note_Id":103
}









# admn.js REQUESTS

###
GET http://localhost:3000/updateAdmin/users

###
GET http://localhost:3000/updateAdmin/forms


###
GET http://localhost:3000/updateAdmin/editForm

###
POST http://localhost:3000/updateAdmin/addForm
Content-Type: application/json

{
    "formName":"as_in_wshop",
    "formId":9002,
    "formAdmins":[303]
}

###
POST http://localhost:3000/updateAdmin/addAdmin
Content-Type: application/json

{
    "formName":"tn_in_tlab",
    "admins":["ins_admin_2"]
}

###
POST http://localhost:3000/updateAdmin/register
Content-Type: application/json

{
    "username":"user12",
    "password":"pass1"
}

###
POST http://localhost:3000/updateAdmin/deleteUser
Content-Type: application/json

{
    "username":"user12"
}


###
GET http://localhost:3000/api/editableForms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMSwidXNlcm5hbWUiOiJ1c2VyMSIsImlhdCI6MTY3NTMyMDk3NSwiZXhwIjoxNjc1MzI0NTc1fQ.OeNL5dfbEcWCDB6moFMG8t-ylilrSwlH5iX4wx1zsD0